<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WebAppDir>$(MSBuildThisFileDirectory)webapp</WebAppDir>
    <AssemblyName>Avalonia.Browser</AssemblyName>
    <Version>12.1.1</Version>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)/avalonia.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <NoWarn>$(NoWarn);AVA3001</NoWarn>
    <DotNetJsApi>true</DotNetJsApi>
    <_targetOS>browser</_targetOS>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <PropertyGroup>
    <AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
    <Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>true</Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.HarfBuzz" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="HarfBuzzSharp" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" />
  </ItemGroup>

  <Target Name="BunInstall" Inputs="$(WebAppDir)/package.json" Outputs="$(WebAppDir)/node_modules/.install-stamp">
    <!-- We use bun packages as .NET tool, to avoid preinstalled node.js dependency -->
    <Exec Command="dnx Bun.Unofficial.Tool --yes -- install" WorkingDirectory="$(WebAppDir)" />
    <!-- Write the stamp file, so incremental builds work -->
    <Touch Files="$(WebAppDir)/node_modules/.install-stamp" AlwaysCreate="true" />
  </Target>
  <Target Name="BunRunBuild" DependsOnTargets="BunInstall" BeforeTargets="DispatchToInnerBuilds">
    <Exec Command="dnx Bun.Unofficial.Tool build.js" WorkingDirectory="$(WebAppDir)" />
  </Target>
  <Target Name="IncludeStaticWebAssets" DependsOnTargets="BunRunBuild" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <StaticWebAssets Include="staticwebassets/**/*.*" />
      <ContentWithTargetPath Include="@(StaticWebAssets)" TargetPath="%(Filename)%(Extension)">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      </ContentWithTargetPath>
    </ItemGroup>
  </Target>
</Project>
